### ISSUE TITLE
Doubt about Orion,Pep Proxy and Authzforce

### ISSUE THREAD

**Issue by fernandorr21** [davidjbrossard/java-json-pep-sdk#6]
Hi, I'm Fernando, did you do this with the solution that they proposed to you in stackoverflow?
Stackoverflow solution:
Now here is the tricky bit, you will need to amend the code of your PEP proxy to ensure you can pass the the value of the "abnormal" attribute so that Authzforce can adjudicate.

The logic will need to be something like this:

1) Whenever the PEP Proxy is invoked, within the PEP Proxy make a direct call to Orion to retrieve the current attribute value.
2) Within your PEP Proxy amend the XML creation function to add the relevant attribute.
3) Call Authzforce to check if the request is permitted

can yo do the number 1 and 2?

**Comment by davidjbrossard** [comment]
This SDK is generic. It means it can be used to do whatever you like from creating a XACML request. The SDK is JSON-based so it won't work if you're looking to create an XML XACML request. The SDK can definitely be used to call out to AuthZForce. I would reach out to @cdanger who is the author behind AuthZForce.
